{{- if not (lookup "scheduling.k8s.io/v1" "PriorityClass" "" "high-priority") }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "Used for core rails web service pods only."
{{- end }}