apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.load_balancer.name  }}
  annotations:
{{- if and (eq .Values.provider.name "aws") .Values.load_balancer.internal }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
{{- else if and (eq .Values.provider.name "azure") .Values.load_balancer.internal }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
{{- else if and (eq .Values.provider.name "google") .Values.load_balancer.internal }}
    cloud.google.com/load-balancer-type: "Internal"
{{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: {{ .Values.load_balancer.externalTrafficPolicy }}
  selector:
    app: {{ .Values.load_balancer.label }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Values.load_balancer.ports.http_name }}
      protocol: {{ .Values.load_balancer.ports.http_protocol }}
      port: {{ .Values.load_balancer.ports.http_port }}
    - name: {{ .Values.load_balancer.ports.https_name }}
      protocol:  {{ .Values.load_balancer.ports.https_protocol }}
      port:   {{ .Values.load_balancer.ports.https_port }}
